name: Snyk scan

on:
  push:
    branches: [ "main" ]
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [ "main" ]
  schedule:
    - cron: '28 6 * * 1'

jobs:
  snyk:
    permissions:
      contents: read # for actions/checkout to fetch code
      security-events: write # for github/codeql-action/upload-sarif to upload SARIF results
      actions: read # only required for a private repository by github/codeql-action/upload-sarif to get the Action run status

    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./aiobastion
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v4

      - name:  Setup Snyk  🐕
        uses: snyk/actions/setup@master

      - name: Snyk dependency scan 🛡️
        run: |
          snyk test --file=../uv.lock --package-manager=uv --dev --sarif-file-output=snyk.sarif
          ls
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}


      - name: Upload result to GitHub Code Scanning 📡
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: ./aiobastion/snyk.sarif